### PR TITLE
Adding ability to search by first and last name

### PR DESCRIPTION
**Pull request by alexspiers**

### CODE REVIEW

**Comment by SgtCoDFish** [comment]
Thanks for this! I'll have a look at it tomorrow, up to my eyeballs in C++ atm!

**Comment by alexspiers** [comment]
No prob just though that being able to search by name would be more helpful than just being able to search by email

**Comment by alexspiers** [comment]
I've just completed the User Admin Backend issue. Plus is there any way for a contributor to claim an issue or does it have to be assigned?

**Comment by SgtCoDFish** [comment]
I think only admins can assign them. Sorry for the delay on this, I'll get it loaded and have a look now!

**Pull request merged**
